name: linters
on: push 

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_PYLINT: True
          VALIDATE_PYTHON: True
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

